ProjectMangaSmurf/Models/BoTruyen.cs
using System;
using System.Collections.Generic;

namespace ProjectMangaSmurf.Models;

public partial class BoTruyen
{
    public string IdBo { get; set; } = null!;

    public string TenBo { get; set; } = null!;

    public byte Dotuoi { get; set; }

    public string IdTg { get; set; } = null!;

    public string Mota { get; set; } = null!;

    public double TkDanhgia { get; set; }

    public int TkTheodoi { get; set; }

    public int TongLuotXem { get; set; }

    public string? AnhBia { get; set; } 

    public string? AnhBanner { get; set; } 

    public bool TtPemium { get; set; }

    public byte TrangThai { get; set; }

    public bool Active { get; set; }

    public string? Listloai { get; set; }

    public virtual ICollection<Chapter> Chapters { get; set; } = new List<Chapter>();

    public virtual ICollection<CtBoTruyen> CtBoTruyens { get; set; } = new List<CtBoTruyen>();

    public virtual ICollection<CtLoaiTruyen> CtLoaiTruyens { get; set; } = new List<CtLoaiTruyen>();

    public virtual TacGium? IdTgNavigation { get; set; } 
}

ProjectMangaSmurf/Models/Chapter.cs
using System;
using System.Collections.Generic;

namespace ProjectMangaSmurf.Models;

public partial class Chapter
{
    public string IdBo { get; set; } = null!;

    public int SttChap { get; set; }

    public string TenChap { get; set; } = null!;

    public string? ChapterContent { get; set; }

    public DateTime ThoiGian { get; set; }

    public byte? TrangThai { get; set; }

    public bool TtPemium { get; set; }

    public byte? TicketCost { get; set; }

    public int TkLuotxem { get; set; }

    public bool Active { get; set; }

    public virtual ICollection<CtChapter> CtChapters { get; set; } = new List<CtChapter>();

    public virtual ICollection<CtHoatDong> CtHoatDongs { get; set; } = new List<CtHoatDong>();

    public virtual BoTruyen? IdBoNavigation { get; set; } 
}

ProjectMangaSmurf/Models/CtBoTruyen.cs
using System;
using System.Collections.Generic;

namespace ProjectMangaSmurf.Models;

public partial class CtBoTruyen
{
    public string IdUser { get; set; } = null!;

    public string IbBo { get; set; } = null!;

    public bool Theodoi { get; set; }

    public byte DanhGia { get; set; }

    public string LsMoi { get; set; } = null!;

    public virtual BoTruyen IbBoNavigation { get; set; } = null!;

    public virtual KhachHang IdUserNavigation { get; set; } = null!;
}

ProjectMangaSmurf/Models/ViewModels/ChapterViewModel.cs
namespace ProjectMangaSmurf.Models.ViewModels
{
    public class ChapterViewModel
    {
        public string IdBo { get; set; } = null!;
        public int SttChap { get; set; }
        public string TenChap { get; set; } = null!;
        public string? ChapterContent { get; set; }
        public DateTime ThoiGian { get; set; } = DateTime.Now;
        public byte? TrangThai { get; set; }
        public bool TtPemium { get; set; }
        public byte? TicketCost { get; set; }
        public int TkLuotxem { get; set; }
        public bool Active { get; set; }
        public List<IFormFile> Images { get; set; } = new List<IFormFile>();
    }
}

ProjectMangaSmurf/Controllers/BoTruyenController.cs
using ProjectMangaSmurf.Models;
using ProjectMangaSmurf.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Http;
using ProjectMangaSmurf.Data;
using Newtonsoft.Json;
using System.Text.RegularExpressions;
using System.Net;
using System.Diagnostics;
namespace ProjectMangaSmurf.Controllers
{
    public class BoTruyenController : Controller
    {
        private readonly IboTruyenRepository _botruyenrepository;
        private readonly ICTBoTruyenRepository _cTBoTruyenRepository;
        private readonly IChapterRepository _chapterrepository;
        private readonly IKhachHangRepository _khachhangrepository;
        private readonly IHopdongRepository _hopdongRepository;
        private readonly IBookRecommendationRepository _recommendationRepository;
        private readonly ProjectDBContext _context;


        public BoTruyenController(  ProjectDBContext db,
                                    IboTruyenRepository botruyenrepository, 
                                    IChapterRepository chapterrepository, 
                                    IKhachHangRepository khachHangRepository, 
                                    ICTBoTruyenRepository cTBoTruyenRepository, 
                                    IHopdongRepository hopdongRepository,
                                    IHttpClientFactory clientFactory, 
                                    IBookRecommendationRepository recommendationRepository)
        {
            _context = db;
            _botruyenrepository = botruyenrepository;
            _chapterrepository = chapterrepository;
            _khachhangrepository = khachHangRepository;
            _cTBoTruyenRepository = cTBoTruyenRepository;
            _hopdongRepository = hopdongRepository;
            _recommendationRepository = recommendationRepository;
        }
        public static int ExtractNumberFromId(string id)
        {
            var match = Regex.Match(id, "^BT([0-9]+)$");
            if (match.Success)
            {
                return int.Parse(match.Groups[1].Value);
            }
            throw new ArgumentException("ID không hợp lệ");
        }
        public async Task<IActionResult> Index()
        {
            using var transaction = _context.Database.BeginTransaction(); 
            try
            {
                var listBotruyen = await _botruyenrepository.GetAllAsync();
                var listLoaiTruyen = await _botruyenrepository.GetAllLoaiTruyens();
                ViewBag.LoaiTruyen = listLoaiTruyen;

                var userId = HttpContext.Session.GetString("IdKH");
                if (userId != null)
                {

                    ViewBag.kh = await _khachhangrepository.GetByIdAsync(userId);
                    ViewBag.pay = await _hopdongRepository.GetPaymentByIdAsync(userId);
                    ViewBag.IdKH = HttpContext.Session.GetString("IdKH");
                }
                else
                {
                    ViewBag.kh = null;
                    ViewBag.IdKH = null;
                }

                var truyenMax = await _botruyenrepository.GetBoTruyenWithMaxViewsAsync();

                var bookId = ExtractNumberFromId(truyenMax.IdBo);
                var recommendations = await _recommendationRepository.GetRecommendationsAsync(bookId);

                List<BoTruyen> list = new List<BoTruyen>();

                foreach (var r in recommendations)
                {
                    var idBo = CreateIdFromNumber(r);
                    BoTruyen bt = await _botruyenrepository.GetByIdAsync(idBo);
                    if (bt != null)
                    {
                        list.Add(bt);
                    }
                }
                ViewBag.list = list;
                ViewBag.MaxView = truyenMax;
                return View(listBotruyen);
            }
            catch (Exception ex)
            {
                transaction.Rollback();
                return RedirectToAction("Error", "Home");
            }
        }
        public async Task<IActionResult> ListTruyen()
        {
            var listBotruyen = await _botruyenrepository.GetAllAsync();
            return View(listBotruyen);
        }
        public async Task<IActionResult> ListTruyenEarliest()
        {
            var listBotruyen = await _botruyenrepository.GetAllAsyncByChapterEarliest();
            return View(listBotruyen);
        }
        public async Task<IActionResult> ListTruyenTT(int id)
        {
            var listBotruyen = await _botruyenrepository.GetAllTrangThaiAsync(id);
            if(id == 0)
            {
                ViewBag.Topic = "ĐANG TIẾN HÀNH";
            }
            if (id == 1)
            {
                ViewBag.Topic = "ĐÃ HOÀN THÀNH";
            }
            if (id == 2)
            {
                ViewBag.Topic = "THEO LƯỢT ĐỌC";
            }
            if (id == 3)
            {
                ViewBag.Topic = "THEO THỜI GIAN";
            }
            if (id == 4)
            {
                ViewBag.Topic = "THEO ĐÁNH GIÁ";
            }
            return View(listBotruyen);
        }
        public async Task<IActionResult> SearchBoTruyen(string query)
        {
            var results = await _botruyenrepository.SearchByNameAsync(query);
            return Json(results.Select(x => new { id = x.IdBo, img = x.AnhBia, tenBo = x.TenBo, view = x.TongLuotXem }));
        }
        public async Task<IActionResult> Rankings(int id)
        {
            ViewBag.Value = id;
            if (id == 1)
            {
                var listView = await _botruyenrepository.GetRankingAsync();
                return View(listView);
            }
            if (id == 2)
            {
                var listFollow = await _botruyenrepository.GetAllAsyncByFollow();
                return View(listFollow);
            }
            if (id == 3)
            {
                var listRate = await _botruyenrepository.GetAllAsyncByRate();
                return View(listRate);
            }
            if (id == 4)
            {
                var listToday = await _botruyenrepository.GetAllAsyncByDay();
                return View(listToday);
            }
            if (id == 5)
            {
                var listMonth = await _botruyenrepository.GetAllAsyncByMonth();
                return View(listMonth);
            }
            var listBotruyen = await _botruyenrepository.GetRankingAsync();
            return View(listBotruyen);
        }
        public async Task<IActionResult> Trending()
        {
            var listBotruyen = await _botruyenrepository.GetTrendingAsync();
            return View(listBotruyen);
        }
        public async Task<IActionResult> ListTopic(string id)
        {
            var listBotruyen = await _botruyenrepository.GetAllByTopic(id);
            var loai = await _botruyenrepository.GetLoaiByNameAsync(id);
            ViewBag.Topic = loai.TenLoai.ToUpper();
            return View(listBotruyen);
        }
        public async Task<IActionResult> ListBirth(int number)
        {
            var listBotruyen = await _botruyenrepository.GetAllByBirth(number);
            if (number == 0)
                ViewBag.Topic = "MỌI ĐỘ TUỔI";
            if (number == 5)
                ViewBag.Topic = "TRẺ EM";
            if (number == 12)
                ViewBag.Topic = "THIẾU NIÊN";
            if (number == 16)
                ViewBag.Topic = "BẠO LỰC";
            if (number == 18)
                ViewBag.Topic = "TRƯỞNG THÀNH";
            return View(listBotruyen);
        }
        private string CreateIdFromNumber(int number)
        {
            return "BT" + number.ToString("D8");
        }
        public async Task<IActionResult> CTBoTruyen(string id)
        {
            using (var transaction = _context.Database.BeginTransaction())
            {
                try
                {
                    var Botruyen = await _botruyenrepository.GetByIdAsync(id);
                    if (Botruyen == null)
                    {
                        return NotFound();
                    }

                    var kh = HttpContext.Session.GetString("IdKH");
                    if (kh != null)
                    {
                        var khtmp = await _khachhangrepository.GetByIdAsync(kh);
                        var findct = _cTBoTruyenRepository.GetByIdFollowAsync(khtmp.IdUser, id);
                        if (await findct != null)
                        {
                            var ls = await findct;
                            ViewBag.follow = true;
                            ViewBag.next = ls.LsMoi;
                        }
                        else
                        {
                            ViewBag.follow = false;
                        }
                        var bookId = ExtractNumberFromId(id);
                        var recommendations = await _recommendationRepository.GetRecommendationsAsync(bookId);

                        List<BoTruyen> list = new List<BoTruyen>();

                        foreach (var r in recommendations)
                        {
                            var idBo = CreateIdFromNumber(r);
                            BoTruyen bt = await _botruyenrepository.GetByIdAsync(idBo);
                            if (bt != null)
                            {
                                list.Add(bt);
                            }
                        }

                        var rating = await _cTBoTruyenRepository.GetByIdAsync(kh, id);
                        if(rating!= null)
                        {
                            ViewBag.rating = rating.DanhGia;
                        }
                        else
                        {
                            ViewBag.rating = "0";
                        }

                        ViewBag.list = list;
                        ViewBag.premium = khtmp.ActivePremium;

ProjectMangaSmurf/Views/BoTruyen/ListTruyen.cshtml
@model IEnumerable<ProjectMangaSmurf.Models.BoTruyen>
@using ProjectMangaSmurf.Repository
@inject IboTruyenRepository boTruyenRepository
@inject IChapterRepository chapterRepository

<link href="~/css/styleList.css" rel="stylesheet" />


<div class=" main__top section">
    <div class=" list__container containers list">
        <div class="top__content">
            <h2 class="section__subtitle">CẬP NHẬT MỚI NHẤT</h2>
            <div class="controls">
                <div class="dropdown">
                    <button class="btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="ri-menu-2-fill"></i> STATUS
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyen">Tất cả</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="1">Hoàn thành</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="0">Đang tiến hành</a></li>
                    </ul>
                </div>
                    <div class="dropdown">
                        <button class="btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="ri-equalizer-2-line"></i> FILTER
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end" style="max-height:150px;">
                            <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="3">Theo thời gian</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="2">View</a></li>
                            <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="4">Đánh giá</a></li>
                        </ul>
                    </div>
            </div>
        </div>
        <div class="container w-100">
            <div class="row justify-content-center">
                @foreach (var botruyen in Model)
                {
                    <div class="item col-2 update-item">
                        <a asp-action="CTBoTruyen" asp-route-id="@botruyen.IdBo">
                            <figure>
                                @{
                                    var EarliestChap = chapterRepository.GetChapterEarliestByIdAsync(botruyen.IdBo);
                                    if (EarliestChap != null)
                                    {
                                        var time = chapterRepository.CalculateTimeAgo(EarliestChap.ThoiGian);
                                        if (!string.IsNullOrEmpty(botruyen.AnhBia))
                                        {
                                            <img loading="lazy" src="@botruyen.AnhBia" alt="truyen Image" />
                                        }
                                        <figcaption>
                                            <h6 class="item-title"><a href="#">@botruyen.TenBo</a></h6>

                                            <a class="item-chapter" style="font-size: 13px;">
                                                <span class="chap" style="margin-right: 10px; ">chap @EarliestChap.SttChap</span>
                                                <span class="time">@time</span>
                                            </a>
                                        </figcaption>
                                    }
                                    else
                                    {
                                        if (!string.IsNullOrEmpty(botruyen.AnhBia))
                                        {
                                            <img loading="lazy" src="@botruyen.AnhBia" alt="truyen Image" />
                                        }
                                        <figcaption>
                                            <h6 class="item-title"><a href="#">@botruyen.TenBo</a></h6>

                                            <a class="item-chapter" style="font-size: 13px;">
                                                <span class="chap" style="margin-right: 10px; ">chap ...</span>
                                                <span class="time">... giờ trước</span>
                                            </a>
                                        </figcaption>
                                    }
                                }
                            </figure>
                        </a>
                    </div>
                }
            </div>
        </div>
        <ul class="listPage">
        </ul>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js" integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@* <script src="/js/script.js"></script> *@
<script src="/js/ScriptShowList.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>

ProjectMangaSmurf/Views/BoTruyen/ListTruyenEarliest.cshtml
@model IEnumerable<ProjectMangaSmurf.Models.BoTruyen>
@using ProjectMangaSmurf.Repository
@inject IboTruyenRepository boTruyenRepository
@inject IChapterRepository chapterRepository

<link href="~/css/styleList.css" rel="stylesheet" />

<div class=" main__top section">
    <div class=" list__container containers list">
        <div class="top__content">
            <span class="section__subtitle">DANH SÁCH TRUYỆN MỚI CẬP NHẬT</span>
            <div class="controls">
                <div class="dropdown">
                    <button class="btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="ri-menu-2-fill"></i> STATUS
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyen">Tất cả</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="1">Hoàn thành</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="0">Đang tiến hành</a></li>
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="ri-equalizer-2-line"></i> FILTER
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end" style="max-height:150px;">
                        <li><a class="dropdown-item" href="#">Theo thời gian</a></li>
                        <li><a class="dropdown-item" href="#">View</a></li>
                        <li><a class="dropdown-item" href="#">Đánh giá</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container w-100">
            <div class="row justify-content-center">
                @foreach (var botruyen in Model)
                {
                    <div class="item col-2 update-item">
                        <a asp-action="CTBoTruyen" asp-route-id="@botruyen.IdBo">
                            <figure>
                                @{
                                    var EarliestChap = chapterRepository.GetChapterEarliestByIdAsync(botruyen.IdBo);
                                    if (EarliestChap != null)
                                    {
                                        var time = chapterRepository.CalculateTimeAgo(EarliestChap.ThoiGian);
                                        if (!string.IsNullOrEmpty(botruyen.AnhBia))
                                        {
                                            <img loading="lazy" src="@botruyen.AnhBia" alt="truyen Image" />
                                        }
                                        <figcaption>
                                            <h6 class="item-title"><a href="#">@botruyen.TenBo</a></h6>

                                            <a class="item-chapter" style="font-size: 13px;">
                                                <span class="chap" style="margin-right: 10px; ">chap @EarliestChap.SttChap</span>
                                                <span class="time">@time</span>
                                            </a>
                                        </figcaption>
                                    }
                                    else
                                    {
                                        if (!string.IsNullOrEmpty(botruyen.AnhBia))
                                        {
                                            <img loading="lazy" src="@botruyen.AnhBia" alt="truyen Image" />
                                        }
                                        <figcaption>
                                            <h6 class="item-title"><a href="#">@botruyen.TenBo</a></h6>

                                            <a class="item-chapter" style="font-size: 13px;">
                                                <span class="chap" style="margin-right: 10px; ">chap ...</span>
                                                <span class="time">... giờ trước</span>
                                            </a>
                                        </figcaption>
                                    }
                                }
                            </figure>
                        </a>
                    </div>
                }
            </div>
        </div>
        <ul class="listPage">
        </ul>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js" integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="/js/script.js"></script>
<script src="/js/ScriptShowList.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>

ProjectMangaSmurf/Views/BoTruyen/ListTruyenTT.cshtml
@model IEnumerable<ProjectMangaSmurf.Models.BoTruyen>
@using ProjectMangaSmurf.Repository
@inject IboTruyenRepository boTruyenRepository
@inject IChapterRepository chapterRepository

<link href="~/css/styleList.css" rel="stylesheet" />
<div class=" main__top section">
    <div class=" list__container containers list">
        <div class="top__content">
            <h2 class="section__subtitle">CẬP NHẬT MỚI NHẤT <span style="color: #9858F1;">@ViewBag.Topic</span></h2>
            <div class="controls">                                                              
                <div class="dropdown">
                    <button class="btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="ri-menu-2-fill"></i> STATUS
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyen">Tất cả</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="1">Hoàn thành</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="0">Đang tiến hành</a></li>
                    </ul>
                </div>
                <div class="dropdown">
                    <button class="btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="ri-equalizer-2-line"></i> FILTER
                    </button>
                    <ul class="dropdown-menu dropdown-menu-end" style="max-height:150px;">
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="3">Theo thời gian</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="2">View</a></li>
                        <li><a class="dropdown-item" asp-area="" asp-controller="BoTruyen" asp-action="ListTruyenTT" asp-route-id="4">Đánh giá</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container w-100">
            <div class="row justify-content-center">
                @foreach (var botruyen in Model)
                {
                    <div class="item col-2 update-item">
                        <a asp-action="CTBoTruyen" asp-route-id="@botruyen.IdBo">
                            <figure>
                                @{
                                    var EarliestChap = chapterRepository.GetChapterEarliestByIdAsync(botruyen.IdBo);
                                    if (EarliestChap != null)
                                    {
                                        var time = chapterRepository.CalculateTimeAgo(EarliestChap.ThoiGian);
                                        if (!string.IsNullOrEmpty(botruyen.AnhBia))
                                        {
                                            <img loading="lazy" src="@botruyen.AnhBia" alt="truyen Image" />
                                        }
                                        <figcaption>
                                            <h6 class="item-title"><a href="#">@botruyen.TenBo</a></h6>

                                            <a class="item-chapter" style="font-size: 13px;">
                                                <span class="chap" style="margin-right: 10px; ">chap @EarliestChap.SttChap</span>
                                                <span class="time">@time</span>
                                            </a>
                                        </figcaption>
                                    }
                                    else
                                    {
                                        if (!string.IsNullOrEmpty(botruyen.AnhBia))
                                        {
                                            <img loading="lazy" src="@botruyen.AnhBia" alt="truyen Image" />
                                        }
                                        <figcaption>
                                            <h6 class="item-title"><a href="#">@botruyen.TenBo</a></h6>

                                            <a class="item-chapter" style="font-size: 13px;">
                                                <span class="chap" style="margin-right: 10px; ">chap ...</span>
                                                <span class="time">... giờ trước</span>
                                            </a>
                                        </figcaption>
                                    }
                                }
                            </figure>
                        </a>
                    </div>
                }
            </div>
        </div>
        <ul class="listPage">
        </ul>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js" integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="/js/script.js"></script>
<script src="/js/ScriptShowList.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>